### ISSUE TITLE
Difficult to download from Baidu for a westerner :)

### ISSUE THREAD

**Issue by r-lomba** [violet-day/tensorflow-crnn#2]
Hi, I'd be very interested in downloading the pre-trained model you made available on Baidu, but I have serious difficulties to create an account, sign in etc, because I can't read Chinese, and also sometimes there are Chinese captchas that I can't write in.

I'd be grateful if you could provide a different way for me to access the files.

In any case, thanks!

**Comment by violet-day** [comment]
Pretrain model is just a demo, can't infer Chinese captchas.
If you want your own Chinese captchas model, you may train yourself.
